#!/usr/bin/env bash
# Propose cut points for slicing an adverts compilation into individual clips.
# Runs ffmpeg blackdetect + silencedetect over the file, then annotates each
# candidate cut with the resulting clip length (SHORT <8s / LONG >60s) so
# problems are visible before splitting. This is a starting point, not a
# final cut list — old compilations rarely have clean black/silence between
# every ad, so expect to hand-adjust the output.
#
# Usage: detect_ad_breaks.sh <compilation-file> [output-timestamps-file]

set -euo pipefail

if [[ $# -lt 1 ]]; then
    echo "Usage: $0 <compilation-file> [output-timestamps-file]" >&2
    exit 1
fi

input="$1"
output="${2:-${input%.*}.cuts.txt}"

if [[ ! -f "$input" ]]; then
    echo "Error: input file not found: $input" >&2
    exit 1
fi

echo "Scanning $input for black frames and silence (this reads the whole file, may take a while)..."

raw="${output}.raw"
ffmpeg -i "$input" -vf "blackdetect=d=0.15:pic_th=0.98" -af "silencedetect=noise=-30dB:d=0.3" \
    -f null - 2> >(grep -E "blackdetect|silencedetect" > "$raw") || true

duration=$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "$input")

python3 - "$input" "$raw" "$duration" "$output" <<'PYEOF'
import sys

input_path, raw_path, duration, output_path = sys.argv[1:5]
duration = float(duration)

cuts = []
with open(raw_path) as f:
    for line in f:
        if "black_start:" in line:
            for tok in line.split():
                if tok.startswith("black_start:"):
                    cuts.append(float(tok.split(":", 1)[1]))
# A black frame right at file start is the compilation opening on black,
# not a real boundary between two ads — drop it like the rest of the file.
cuts = sorted(set(c for c in cuts if c > 1))

def hms(s):
    h = int(s // 3600)
    m = int((s % 3600) // 60)
    sec = s % 60
    return f"{h:02d}:{m:02d}:{sec:05.2f}"

bounds = [0.0] + cuts + [duration]

out = [
    f"# Candidate cut points for: {input_path}",
    "# Generated by detect_ad_breaks.sh — REVIEW AND ADJUST before splitting.",
    "# One timestamp (seconds) per line = a boundary between two ads.",
    "# Each cut line below is annotated with the resulting clip length so you",
    "# can spot problems before running split_ads.sh:",
    "#   SHORT (<8s)  -> likely a spurious double-detection, consider deleting",
    "#                   the timestamp that starts this too-short clip",
    "#   LONG (>60s)  -> likely two ads got merged, scrub through this range",
    "#                   in a player and insert a missing cut timestamp",
    "#",
    "# --- Edit below this line: one cut timestamp per line ---",
]

for i in range(len(bounds) - 1):
    if i == 0:
        continue  # bounds[0] is 0.0 (start of file), not a cut line
    start, end = bounds[i], bounds[i + 1]
    dur = end - start
    flag = ""
    if dur < 8:
        flag = f"   # <- SHORT, clip would be only {dur:.1f}s ({hms(start)} -> {hms(end)})"
    elif dur > 60:
        flag = f"   # <- LONG, clip would be {dur:.1f}s ({hms(start)} -> {hms(end)}) - check for a missed cut"
    out.append(f"{cuts[i - 1]}{flag}")

with open(output_path, "w") as f:
    f.write("\n".join(out) + "\n")
PYEOF

rm -f "$raw"

echo "Candidate cut points written to: $output"
echo "Open it, delete/add/adjust timestamps until each pair of consecutive lines"
echo "brackets exactly one advert, then run split_ads.sh against it."
