[Test Channel]
	DELIVERY_SYSTEM = DVBT
	FREQUENCY = 610000000
	BANDWIDTH_HZ = 6000000
	MODULATION = QPSK
	GUARD_INTERVAL = 1/4
	INVERSION = AUTO
	CODE_RATE_HP = 1/2
	CODE_RATE_LP = 1/2
	TRANSMISSION_MODE = 2K
	HIERARCHY = NONE
